image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - publish

before_script:
  - apk add bash git
  - /bin/bash .utilities/check.sh

build:
  stage: build
  script: /bin/bash -e .utilities/build.sh
  only:
    - tags
  artifacts:
    paths:
      - "$CI_PROJECT_NAME.tar"

test:
  stage: test
  script: /bin/bash -e .utilities/test.sh
  only:
    - tags
    - schedules
  artifacts:
    paths:
      - "$CI_PROJECT_NAME.tar"

publish:
  stage: publish
  script: /bin/bash -e .utilities/publish.sh
  only:
    - tags
  artifacts:
    paths:
      - "$CI_PROJECT_NAME.tar"

#update_docker_hub_full_description:
#  stage: publish
#  script: /bin/bash -e .utilities/update-docker-hub-full-description.sh
#  only:
#    - master

description_templater:
  image: python/3.8-alpine
  stage: build
  script: sh -e .utilities/templates/templater.sh
  only:
    - enhance--documentations-templates
  artifacts:
    paths:
      - "*.description"
