image: docker:latest

services:
  - docker:dind

.parallel:
  parallel:
    matrix:
      - TARGET: [oldstable, stable, unstable]

stages:
  - build
  - test
  - release

before_script:
  - apk add bash git curl jq make

build:
  stage: build
  script:
    - make build
    - make save
  extends: .parallel
  only:
    - merge_requests
    - tags
  artifacts:
    paths:
      - "tarballs/"

test:
  stage: test
  script:
    - make load
    - make build-test
    - make test
  extends: .parallel
  needs:
    - job: build
      parallel:
        matrix:
          - TARGET: oldstable
          - TARGET: stable
          - TARGET: unstable
  only:
    - merge_requests
    - tags
  artifacts:
    paths:
      - tarballs/

publish-images:
  stage: release
  script:
    - make load
    - make publish-images
  needs:
    - job: build
      parallel:
        matrix:
          - TARGET: oldstable
          - TARGET: stable
          - TARGET: unstable
    - job: test
  extends: .parallel
  only:
    - tags
  artifacts:
    paths:
      - tarballs/
      - versions/*

make-documents:
  stage: release
  script:
    - apk add py3-jinja2
    - make documents
  needs:
    - job: publish-images
      parallel:
        matrix:
          - TARGET: oldstable
          - TARGET: stable
          - TARGET: unstable
  only:
    - tags
  artifacts:
    paths:
      - versions/*
      - documentations/*.md

publish-documents:
  stage: release
  script:
    - make publish-documents
  needs:
    - job: make-documents
  only:
    - tags
  artifacts:
    paths:
      - documentations/*.md