image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - publish

before_script:
  - apk add bash

build:
  stage: build
  script: /bin/bash .utilities/build.sh
  only:
    - tags
    - schedules
    - milestone--2.0
  artifacts:
    paths:
      - $CI_PROJECT_NAME.tar

test:
  stage: test
  script: /bin/bash .utilities/test.sh
  only:
    - tags
    - schedules
    - milestone--2.0
  artifacts:
    paths:
      - $CI_PROJECT_NAME.tar

publish:
  stage: publish
  script: /bin/bash .utilities/publish.sh
  only:
    - tags
    - schedules
  artifacts:
    paths:
      - $CI_PROJECT_NAME.tar

update_docker_hub_full_description:
  stage: publish
  script: /bin/bash .utilities/update-docker-hub-full-description.sh
  only:
    - master
