image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - publish

before_script:
  - apk add bash git
  - /bin/bash .utilities/check.sh

build.tags:
  stage: build
  script: /bin/bash -e .utilities/build.sh
  only:
    - tags
  artifacts:
    paths:
      - $CI_PROJECT_NAME.tar

test:
  stage: test
  script: /bin/bash -e .utilities/test.sh
  only:
    - tags
    - schedules
  artifacts:
    paths:
      - $CI_PROJECT_NAME.tar

publish.tags:
  stage: publish
  script: /bin/bash -e .utilities/publish.sh
  only:
    - tags
  artifacts:
    paths:
      - $CI_PROJECT_NAME.tar

debugging:
  stage: test
  script: echo $CI_PROJECT_URL
  only:
    - enhancement--microbadger-badges

#update_docker_hub_full_description:
#  stage: publish
#  script: /bin/bash -e .utilities/update-docker-hub-full-description.sh
#  only:
#    - master
